site_name: Cloud4RPi Documentation
site_description: Cloud control panel for your IoT projects.
site_author: Cloud4RPi Team
repo_url: https://github.com/cloud4rpi/docs

pages:
- Home: index.md
- Getting Started:
    - Raspberry Pi: start/rpi.md
    - C.H.I.P.: start/chip.md
    - Omega2: start/o2.md
    - ESP8266:
        - MicroPython: start/esp8266-upy.md
        - PlatformIO: start/esp-pio.md
        - Arduino: start/esp-ino.md
- How To:
    - Raspberry Pi: howto/rpi.md
    - C.H.I.P.: howto/chip.md
    - Omega2: howto/o2.md
- API:
    - Python Library: api/python.md
    - MQTT Protocol: api/mqtt.md
    - HTTP Protocol: api/http.md
- FAQ: faq.md

markdown_extensions:
    - admonition:
    - attr_list:

extra_css: [res/extra.css]
theme: material

copyright: © 2016-2018 Devsoft Baltic OÜ. All rights reserved.
